<?php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
// ------------------------------------------------------------------------- //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

// The name of this module
define("_MI_X_JAWSTATS_NAME","X JAWStats");

// A brief description of this module
define("_MI_X_JAWSTATS_DESC","Module for displaying webstats using jawstats frontend and awstats backend.");

define("_MI_X_JAWSTATS_ADMENU1","Main");
define("_MI_X_JAWSTATS_ADMENU2","Help");
// Title of config items
define('_MI_X_JAWSTATS_SITENAME','Site Name');
define('_MI_X_MOVIE_SITENAMEDSC','Specify the name of your site, minus the http://.');
define('_MI_X_JAWSTATS_STATSPATH','Stats Path');
define('_MI_X_JAWSTATS_STATSPATHDSC','This is the path to the statistics generated by awstats.');
define('_MI_X_JAWSTATS_UPDATEPATH','Update Path');
define('_MI_X_JAWSTATS_UPDATEPATHDSC','This is the path to you awstats.pl file');
define('_MI_X_JAWSTATS_SITEURL', 'Site Url');
define('_MI_X_MOVIE_SITEURLDSC','Specify the url of your site. This includes the http://.');
define('_MI_X_JAWSTATS_FADESPEED','Fade Speed');
define('_MI_X_JAWSTATS_FADESPEEDDSC','This is the fade speed of button effects.');
define('_MI_X_JAWSTATS_HELP', "<table width='100%' cellspacing='1' cellpadding='3' class='outer'>\n
  <tr class='bg3'>
    <td>About X JAWStats</td>
  </tr>
  <tr class='bg1'>
    <td><p>X JAWStats is a module that uses JAWStats and AWStats to display website statistics. JAWStats reads the statistics files of AWStats and displays statistics using php and jquery. AWStats must already be installed and working correctly before you can read the files. </p>
<p>Update the config.php file located in the admin folder. That's all there is to it.</p><p>This module is currenly only compatible with xoops 2.3.</td>
  </tr>
  <tr class='bg3'>
    <td>sname</td>
  </tr>
  <tr class='bg1'>
    <td><p>This is the full name of your website. (www.yoursite.com or subsite.yoursite.com)</p></td>
  </tr>
  <tr class='bg3'>
    <td>spath</td>
  </tr>
  <tr class='bg1'>
    <td><p>This is the path to where awstats generates your statistics. Statistics files look similar to, awstats200901.www.yoursite.com.txt. (/path/to/awstats/statistics/files/)</p></td>
  </tr>
  <tr class='bg3'>
    <td>upath</td>
  </tr>
  <tr class='bg1'>
    <td><p>This is the path to where your awstats.pl file is located on the server. (/path/to/awstats.pl/)</p></td>
  </tr>
  <tr class='bg3'>
    <td>surl</td>
  </tr>
  <tr class='bg1'>
    <td><p>This is the http link of your site. (http://www.yoursite.com or http://subsite.yoursite.com)</p></td>
  </tr>
  <tr class='bg3'>
    <td>fspeed</td>
  </tr>
  <tr class='bg1'>
    <td><p>This is the fade speed of jquery effects. (250)</p></td>
  </tr>
  </table>");

?>

